import Head from "next/head";
import React from "react";
import { AppBar, Box, Container, Toolbar } from "@material-ui/core";
import Typography from "@mui/material/Typography";
import EmojiObjectsOutlinedIcon from "@mui/icons-material/EmojiObjectsOutlined";
import Button from "@mui/material/Button";
import Link from "@mui/material/Link";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>Memorize App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <AppBar>
          <Container maxWidth="xl">
            <Toolbar disableGutters>
              <EmojiObjectsOutlinedIcon
                sx={{ display: { xs: "none", md: "flex" }, mr: 1 }}
              />
              <Typography
                variant="h6"
                noWrap
                component="a"
                href="/"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "monospace",
                  fontWeight: 400,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                MEMORIZE APP
              </Typography>
              <Box sx={{ flexGrow: 1, display: { xs: "none", md: "flex" } }}>
                <button className="button-primary">
                  <Link href="/create">Create Set</Link>
                </button>
                <button className="button-primary">
                  <Link href="/sets">My Sets</Link>
                </button>
                <button className="button-primary">
                  <Link href="/stats">Stats</Link>
                </button>
              </Box>
            </Toolbar>
          </Container>
        </AppBar>
      </header>
      <div style={{ marginTop: "5rem" }}>{children}</div>
    </div>
  );
}
