import { Head } from "next/document";
import React from "react";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <div style={{ padding: "0 2rem", backgroundColor: "#f9f9f9" }}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
      </body>
    </html>
  );
}
