import { AppBar, Box, Container, Toolbar } from "@material-ui/core";
import Typography from "@mui/material/Typography";

import Head from "next/head";
import Image from "next/image";
import FileLoader from "../components/file-loader.component";
import styles from "../styles/Home.module.css";
import EmojiObjectsOutlinedIcon from "@mui/icons-material/EmojiObjectsOutlined";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import LearnComponent from "../components/learn-component";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <AppBar>
          <Container maxWidth="xl">
            <Toolbar disableGutters>
              <EmojiObjectsOutlinedIcon
                sx={{ display: { xs: "none", md: "flex" }, mr: 1 }}
              />
              <Typography
                variant="h6"
                noWrap
                component="a"
                href="/"
                sx={{
                  mr: 2,
                  display: { xs: "none", md: "flex" },
                  fontFamily: "monospace",
                  fontWeight: 400,
                  letterSpacing: ".3rem",
                  color: "inherit",
                  textDecoration: "none",
                }}
              >
                MEMORIZE APP
              </Typography>
              <Box sx={{ flexGrow: 1, display: { xs: "none", md: "flex" } }}>
                <Button
                  variant="contained"
                  sx={{
                    my: 2,
                    overrides: { color: "white" },
                    display: "block",
                  }}
                ></Button>
              </Box>
            </Toolbar>
          </Container>
        </AppBar>
      </header>
      <main className={styles.main}>
        <Card variant="outlined" sx={{ minWidth: 275 }}>
          <CardContent>
            <FileLoader></FileLoader>
          </CardContent>
        </Card>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
